### PR TITLE
Add Continent Models

### PR DESCRIPTION
**Pull request by blag**
* Add `Continent` model
* Add `ForeignKey` to `Continent` onto `Country` model
* Import continents during migration
* Modify migration script to import as a foreign key or abbreviation depending on the type of `Country.continent`

This also allows the user to override the imported continent data before the initial migration (in the `CITIES_CONTINENT_DATA` variable).

### CODE REVIEW

**Comment by blag** [comment]
Bump.

**Comment by yetanotherape** [comment]
Hi! There is a strange `import caching.base` in cities/migrations/0002_continent_models_and_foreign_keys.py that broke migrations.

**Comment by blag** [comment]
@yetanotherape: Thanks for noticing, this is fixed in master.

I'm going to try to create tests for this project in the coming weeks and integrate Travis-CI. Once that's done, little one-off issues like this should be caught before merging.

**Comment by yetanotherape** [comment]
@blag Thanks!

**Pull request merged**
