### PR TITLE
Django 2.0

### PR DESCRIPTION
**Pull request by blag**
Supersedes #185.

### CODE REVIEW

**Comment by tony** [comment]
There are passing tests on Travis-CI that show up as failing.

**Comment by dlionel** [comment]
Happy new year! Is there anything I can do to help with the merge?

**Comment by blag** [comment]
Happy New Year @dlionel!

Yes, you can help out! Please test the code from this PR. I'm specifically looking for two cases, maybe you can help me out:

1. Existing models from a Django 1.x installation. Migration `0011` *should* work just fine, but it might not.
2. Creating a Django 2.0 installation from scratch. All migrations have to work for Django 1.x and Django 2.0, so I'd like to make sure migration `0011` isn't broken for Django 2.0 users.

If you can test either or both of those cases I would greatly appreciate it.

Let me know if you run into any issues during testing and I'll try to help you debug issues as best I can.

**Comment by joehene** [comment]
Thanks for this info.

**Pull request merged**
