### PR TITLE
Honor verbosity in management command

### PR DESCRIPTION
**Pull request by lockie**
Hello!
Sometimes (e.g. in install scripts or Docker environments) the fancy progress bar is not desirable. This little PR adds ability to turn it off when needed, using conventional `--verbosity` switch.

### CODE REVIEW

**Comment by blag** [comment]
I like this, but I think a `--quiet` or `--silent` switch is easier to understand instead of setting `--verbosity=0`. Can you rewrite it to use that instead? I'm happy to merge it in once you do. Thanks!

**Comment by lockie** [comment]
Okay sure.

**Comment by blag** [comment]
Thanks!

**Comment by lockie** [comment]
Thank you :)

**Pull request merged**
