### PR TITLE
Added customizable possibility to import cities without region

### PR DESCRIPTION
**Pull request by eugena**

### CODE REVIEW

**Comment by coderholic** [comment]
Can you give some details about why you want cities and not regions? Have you tested this with the city code? Pretty sure it'll break a bunch of code there.

**Comment by coderholic** [comment]
At the very least https://github.com/coderholic/django-cities/blob/master/cities/models.py#L102 would need to be updated

**Comment by eugena** [comment]
Thanks for your answer. The fact is that, we can't import all interesting cities. For instance,  we've imported 39 cities instead of 1024 for Hong Kong! It's a problem for us, actually. That is why I've offered our unobtrusive patch ;-). Without CITIES_IGNORE_EMPTY_REGIONS = True everything will work as earlier.

About property, yes, a region will be None. Why not? This case can be processed later, in other layer.

**Comment by coderholic** [comment]
Ah ok, so this still imports regions, it just doesn't skip over cities where a region cannot be found?

**Comment by eugena** [comment]
Absolutely ;-)

**Comment by coderholic** [comment]
Cool, that makes a lot of sense :)

**Pull request merged**
